#!/bin/bash
# Preprocess the ~1.33M DICOMs not yet in the WebDataset shards.
#
# Input CSV:  preprocessing/csv_preparation/csv/remaining_to_preprocess.csv
#             (generated by build_remaining_csv.py — 1,334,027 rows)
# Output dir: /hdd2/ahmedaly/preprocessed_remaining/
#
# Run in a tmux session:
#   tmux new-session -s preprocess_remaining
#   bash EchoJEPAv2/preprocessing/launch_remaining_preprocessing.sh
#
# Resume: re-run the same command — progress.csv in the output dir will skip
#         already-processed UUIDs automatically.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CSV="$REPO_ROOT/../preprocessing/csv_preparation/csv/remaining_to_preprocess.csv"
METADATA_CSV="$REPO_ROOT/../preprocessing/dicom_metadata.csv"
ANNOTATIONS_DB="$REPO_ROOT/../preprocessing/json_annotation/annotations.db"
OUTPUT_DIR="/hdd2/ahmedaly/preprocessed_remaining"
NUM_WORKERS=64

echo "=== EchoJEPAv2 Remaining Preprocessing ==="
echo "Input CSV:      $CSV"
echo "Output dir:     $OUTPUT_DIR"
echo "Workers:        $NUM_WORKERS"
echo ""

if [ ! -f "$CSV" ]; then
    echo "ERROR: Input CSV not found: $CSV"
    exit 1
fi

ROWS=$(wc -l < "$CSV")
echo "Rows in CSV: $((ROWS - 1)) DICOMs"

mkdir -p "$OUTPUT_DIR"

PYTHON="/hdd2/ahmedaly/miniconda/envs/icardio/bin/python"

PYTHONPATH="$REPO_ROOT/EchoJEPA" \
"$PYTHON" "$REPO_ROOT/preprocessing/create_webdataset.py" \
    --csv "$CSV" \
    --metadata-csv "$METADATA_CSV" \
    --annotations-db "$ANNOTATIONS_DB" \
    --output-dir "$OUTPUT_DIR" \
    --num-workers "$NUM_WORKERS"

echo ""
echo "=== Preprocessing complete. Rebuilding shard index... ==="
cd "$REPO_ROOT"
PYTHONPATH="$REPO_ROOT/EchoJEPA" \
"$PYTHON" evaluation/build_index.py
echo "=== Done. ==="
