app: vjepa
cpus_per_task: 8
folder: /home/ahmedaly/iCardio/checkpoints/evals/icardio_336px_e200
mem_per_gpu: 48G
nodes: 1
tasks_per_node: 1
num_workers: 6

eval_name: video_classification_frozen
resume_checkpoint: false
tag: icardio-lvidd-e200

experiment:
  classifier:
    task_type: regression
    num_heads: 16
    num_probe_blocks: 4
    num_targets: 1

  data:
    dataset_type: WebDatasetLabeledVideoDataset
    dataset_train:
      - /hdd2/ahmedaly/preprocessed_by_alikhan_for_echojepa
      - /hdd1/ahmedaly/preprocessed_by_alikhan_for_echojepa
    dataset_val:
      - /hdd2/ahmedaly/preprocessed_by_alikhan_for_echojepa
      - /hdd1/ahmedaly/preprocessed_by_alikhan_for_echojepa
    label_csv_train: /home/ahmedaly/iCardio/EchoJEPAv2/training/data_csvs/icardio_lvidd_train.csv
    label_csv_val: /home/ahmedaly/iCardio/EchoJEPAv2/training/data_csvs/icardio_lvidd_val.csv

    steps_per_epoch: 2000
    val_steps_per_epoch: 100
    resolution: 336
    frames_per_clip: 16
    frame_step: 2
    num_segments: 2
    num_views_per_segment: 1

    # LVIDd stats (train set): mean=4.7547 cm, std=0.6158 cm
    target_mean: 4.7547
    target_std: 0.6158

  optimization:
    batch_size: 8
    multihead_kwargs:
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.00005
      start_lr: 0.00005
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.00005
      start_lr: 0.00005
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.00005
      start_lr: 0.00005
      warmup: 0.0
      weight_decay: 0.4

    num_epochs: 20
    use_bfloat16: true
    use_pos_embed: false

model_kwargs:
  checkpoint: /home/ahmedaly/iCardio/checkpoints/pretrain/icardio_vitl16_336px_16f/target_encoder_e200.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: state_dict
      img_temporal_dim_size: null
      model_name: vit_large
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
